---
title: "Group by and Summarize"
author: "Ruilian Zhang"
date: "10/5/2021"
output: github_document
---

```{r}
library(tidyverse)

#embedded figures options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, # the ration of height/length
  out.width = "90%"
)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% # create a month variable (round day down)
  select(name, id, everything())
```


## group_by()

```{r}
weather_df %>% 
  group_by(name)
```


## count some things

```{r}
weather_df %>% 
  group_by(month) %>% # a neat way
  summarize(n_obs = n()) # how many observations in each month group

weather_df %>% 
  count(name) # a quick way
```

It's nice that this is a dataframe
`table` doesn't, and it's bad

```{r}
weather_df %>% 
  pull(name) %>% 
  table()
```

```{r}
weather_df %>% 
  janitor::tabyl(month, name) #like a pivot_wider version
```


## more general summaries

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE), # remove missing values
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```

