---
title: "viz_and_eda"
author: "Ruilian Zhang"
date: "10/5/2021"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

#embedded figures options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```



## Scatterplot

tmax vs tmin

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

you can save ggplots

```{r}
ggp_tmax_tmin = weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_tmax_tmin
```


## Let's fanxy it up

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + # use this color aesthetic for all geometry below
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name) # . is the placeholder
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = .3) +
  facet_grid(. ~ name) +
  geom_smooth(se = FALSE) # turn standard error bars off
```


## Use data manipulation as part of this

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(tmin = tmin * (9 / 5) + 32,
         tmax = tmax * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


## Stacking geoms

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth()
```

```{r}
# show how density is in every particular point
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```


## Univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(. ~ name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)
```

Still with `tmax` and `name`

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

```{r}
# stack density plots, not totally stack
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(alpha = .8, scale = .8)
```


##Embedding plots 

```{r, fig.width = 12}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3)
```

