---
title: "viz_and_eda"
author: "Ruilian Zhang"
date: "10/5/2021"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
library(viridis)

#embedded figures options
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature",
    x = "Min",
    y = "Max",
    caption = "Data from rnoaa package with three stations"
  )
```


## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature",
    x = "Min",
    y = "Max",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_color_hue(
    name = "Location", # name the legend
    h = c(100, 300)) + 
  viridis::scale_color_viridis( # viridis is a color pallette and is good
    name = "Location", 
    discrete = TRUE
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0,15),
    labels = c("-15C", "0", "15")
  ) + 
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )

```


## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature",
    x = "Minimnun daily temp (C)",
    y = "Maximnun daily temp (C)",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_color_viridis_d() +
  # theme_bw() + # change the background to black and white
  # theme_classic()
  theme_minimal() +
  theme(legend.position = "bottom")
```

